name: "Hello Actions"
descritpion: "Greeting"
author: "kacperkan"

inputs:
    MY_NAME:
        description: "Who is to greet"
        required: true
        default: "World"

runs:
    using: "docker"
    image: "Dockerfile"

branding:
    icon: "mic"
    color: "purple"

